### ISSUE TITLE
The AND operation doesn't seem to work...

### ISSUE THREAD

**Issue by reteo** [lawremi/CustomOreGen#107]
Code:

```
<IfCondition condition=':= ((?blockExists("Railcraft:ore:2") | ?blockExists("Railcraft:ore:3") | ?blockExists("Railcraft:ore:4")) &amp; (?blockExists("Railcraft:cube:6"))) '>
```

What this should do, if this is correct, is check to see if any of the Railcraft:ore blocks are present AND if the Railcraft:cube block is present.  If either all ores, or the cube block is missing, then the check should fail.

So far, it is not failing.  Am I doing this wrong, or is there something wrong with expressions?

**Comment by lawremi** [comment]
What about changing the block names to something completely made up, just to verify? Certainly AND does work in the situations we have encountered so far.

**Comment by reteo** [comment]
I see... the distributions disable with the fictional material, while disabled railcraft ores still seem to exist as far as the check is concerned.  Good to know.

**Comment by reteo** [comment]
In that case, everything is working correctly, and you can expect a flood of block-checked configurations shortly
