### ISSUE TITLE
Adding a print command to XML files

### ISSUE THREAD

**Issue by reteo** [lawremi/CustomOreGen#109]
I think it would be extremely useful if a "Print" or "Log" command could be added to the XML as a debugging option.  You can add something like <LOG>"Some text to show up on the minecraft log"</LOG>.  This would make troubleshooting problems a lot easier, as it would allow the config editor to know which config file (and possibly distribution) was being used when the issue struck.  At the moment, if COG crashes while building a world, and it's not because of a specific distribution, you're left in the dark as to which configuration file is spewing the error.

**Comment by lawremi** [comment]
In theory every error should indicate the XML location, at least during config parsing. Is there a specific error that prompted this request?

**Comment by reteo** [comment]
Yeah, and I finally figured it out.  The problem was that it was something I had to manually search through all the configs to find (for word "MISSING\", due to a mis-entry in the spreadsheet), because while the error gives the line number, it does not give the XML file in which the problem happens.

**Comment by lawremi** [comment]
Yea, I could have any exception thrown during validation to return the nme of the distribution...
