### ISSUE TITLE
[Crash]Crash on a fixed location.

### ISSUE THREAD

**Issue by ProgrammedSoul** [lawremi/CustomOreGen#116]
http://pastebin.com/qNhj8k0m
Using 1.2.24 version and the latest recommended forge. I'm not sure is this caused purely by custom ore gen, but that is the only mod name that i could see in the crash report. Basically, I was randomly fly around the world and keep crushing at the same location. After the first crash the server crashed whenever I logged in.
There is a clue that I thought which might be related, which is I pre-gened the map using world boarder  mod after custom ore gen is installed. The crash location is not likely to be the pre-gened chunk through, I don't think I've fly that far.

**Comment by ProgrammedSoul** [comment]
Also as world generation is happened on server side, I don't think this mod need to be client side required. Not saying the mod is bad by any means, but it just make server management a bit easier.

**Comment by ProgrammedSoul** [comment]
Confirmed the crash is caused by custom ore gen as the crash is fixed as the mod is removed. The chunk that's causing the crash is shown in the center of the view:
![2015-11-28_09 28 15](https://cloud.githubusercontent.com/assets/4493654/11452549/78476d24-95b9-11e5-968c-2b134cdd20c1.png)
Also the mod is causing chunk wise glitch looking in project red world generation:
![2015-11-27_20 57 59](https://cloud.githubusercontent.com/assets/4493654/11452552/a2c8d2e0-95b9-11e5-9ce2-4475681d45b2.png)

**Comment by lawremi** [comment]
At least in part. The cause is likely some interaction between mods. COG needs to defer world generation, and that sometimes interacts poorly with other world generation, chunk loaders, etc. Perhaps this is due to corruption in this particular world. Are you able to reproduce reliably in new worlds? Could you get a minimal mod list that reproduces the issue?

**Comment by ProgrammedSoul** [comment]
This crash can be reproduce by load a chunk that is pre-generated by world border mod. It seems world boarder only pre generate the terrain but the ores, so a post generation event will happen when a pre-gened chunk is loaded at the first time. Try minimum mod is kind hard because it can only be done at server, but I'll try it out when I have a chance.

**Comment by lawremi** [comment]
Yea, the problem is that COG wants to check whether a saved chunk has been populated, but Forge will automatically populate the chunk upon load, causing recursion and race conditions. Therefore, there may be no point in checking the populated status of an unloaded chunk. Will look into this.
