### ISSUE TITLE
Custom Ore Gen won't load in custom modpack due to config error

### ISSUE THREAD

**Issue by Qohelethh** [lawremi/CustomOreGen#118]
COG won't load because it thinks its default config files aren't there. They are. I even did a fresh install and deleted everything and started again. Here's the message COG gives.

CustomOreGen has detected an error while trying to load its config files.
At this time you may: 
  (1) Abort loading and close Minecraft (click 'Abort').
  (2) Try to fix the error and then reload the config files (click 'Retry').
  (3) Ignore the error and continue without loading the config files (click 'Ignore').
It is strongly recommended that you do not ignore the error.

------ Error Message ------

CustomOreGen Config Error at Element <Import> [line 398]: No files found matching 'modules/default/ArsMagicka2.xml'.
  in Element <Import> [line 398]
  in Element <Config> [line 33]
  in Document = /home/sebastian/minecraft_server/config/CustomOreGen/CustomOreGen_Config.xml

**Comment by lawremi** [comment]
You need to update your `CustomOreGen_Config.xml`, because `ArsMagicka2.xml` is now `ArsMagica2.xml`.

**Comment by Qohelethh** [comment]
Thank you!
