### ISSUE TITLE
Infinite loops in Veins generation

### ISSUE THREAD

**Issue by LemADEC** [lawremi/CustomOreGen#120]
https://github.com/lawremi/CustomOreGen/blob/master/src/main/java/CustomOreGen/Server/MapGenVeins.java#L568
This function goes into an infinite loop on server as you can see in below profiler screenshot.
![image](https://cloud.githubusercontent.com/assets/4776032/11761731/62f66b1c-a0ce-11e5-8c51-91da13c60510.png)

Any idea which parameters we need to adjust?

**Comment by lawremi** [comment]
It is going to be related to some other mod or configuration, so we will have to narrow things down on your side.

**Comment by LemADEC** [comment]
This is reproduced with my modpack version 8.0.8, available here: http://www.technicpack.net/modpack/tdks-world-war-minecraft.173124

I'm using custom configuration for ores, exclusives with layered veins.
Specifically for Coal, we've this option where MotherlodeSize can be lower than 0:
```
				<Veins name='CoalVeins' inherits='PresetSparseVeins' seed='0xC047'>
					<Description>
						Coal spawns just near the surface, and up into hills and mountains.  The veins are
						long and thick, but sparsely filled with ore and often broken up by caves or depressions
						in the terrain.
					</Description>
					<DrawWireframe>:=vnlaDrawWireframes</DrawWireframe>
					<WireframeColor>0x60101010</WireframeColor>
					<OreBlock block='minecraft:coal_ore' weight='0.65'/>
					<Setting name='MotherlodeFrequency' avg=':= 15.0 * coalFreq * _default_'/>
					<Setting name='MotherlodeSize' avg=':= 2.5 * coalSize * _default_' range=':= 4.5 * coalSize * _default_'/>
					<Setting name='MotherlodeHeight' avg=':= 70/64 * dimension.groundLevel' range=':= 30/64 * dimension.groundLevel' type='normal'/>
					<Setting name='BranchLength' avg=':= 0.20 * _default_' range=':= 0.15 * _default_'/>
					<Setting name='BranchInclination' avg='0' range='0.25'/>
					<Setting name='BranchHeightLimit' avg='30'/>
					<Setting name='SegmentForkLengthMult' avg='0.25' range='0.15' />
					<Setting name='SegmentRadius' avg=':= 0.25 * coalSize * _default_' range=':= 0.20 * coalSize * _default_'/>
					<Setting name='OreDensity' avg='1' range='0'/>
				</Veins>
```
Could this generate an infinite loop?
