### ISSUE TITLE
Negative segment radius in default configuration?

### ISSUE THREAD

**Issue by LemADEC** [lawremi/CustomOreGen#121]
https://github.com/lawremi/CustomOreGen/blob/5d07b8e608828bbdd8e921a8067e050c6ba36c69/src/main/resources/config/CustomOreGen_Config_Default.xml#L339
```
<Setting name='SegmentRadius' avg=':= 0.025 * oreSize' range=':= 0.2 * oreSize'/>
```
This would create segments with a negative radius.
Is the mod truncating to zero or would it crash the server somehow?

**Comment by lawremi** [comment]
Wow, good eyes. Yes, that will likely cause a problem. No one has ever used the HugeVeins preset. The range is probably just a typo. Will fix.
