### ISSUE TITLE
Something about translation

### ISSUE THREAD

**Issue by XieEDeHeiShou** [lawremi/CustomOreGen#130]
I'm a Chinese user,though I myself  can read and understand the lists below "CustomOreGen Options" in English,I'm afraid not all Chinese user could .Is there anything that I can do to this mod to help others use it? 
I cann't find any language file in the jar as other mod,which means I cannot easily localize it. Was there supposed to be or going to be one?Or may I change something more deeply to make it localized and then repost it at MCBBS(A Chinese unofficial Minecraft forum)?

**Comment by reteo** [comment]
I don't really know much about localization, but if you want to tackle the project, [this](https://github.com/reteo/Sprocket) should make the project much easier.  You can find the INI files from which nearly all the current COG configs spring from [here](https://github.com/reteo/Sprocket/tree/master/configs/Examples/INI).  Simply replace English with Chinese, run the INI through Sprocket, and you have your localized versions of the configs.

**Comment by lawremi** [comment]
See https://github.com/lawremi/CustomOreGen/wiki/Localization. If that works for you, please close this issue.
