### ISSUE TITLE
Something about VanillaMinecraft.xml

### ISSUE THREAD

**Issue by XieEDeHeiShou** [lawremi/CustomOreGen#131]
I just found there are double
Choice value='Cloud' displayValue='Strategic Cloud'
                Description
                        Large irregular clouds filled lightly with ore.
                  /Description
              /Choice
below
!-- Coal Configuration UI Starting --
in the VanillaMinecraft.xml.
was it a Mistake? or designed?

**Comment by reteo** [comment]
I see the option for sparse veins ("Large *veins* filled very lightly with ore.") and strategic clouds ("Large *irregular clouds* filled lightly with ore.").  Are you certain they both say clouds?

**Comment by XieEDeHeiShou** [comment]
Sorry..My mistake ...

**Comment by XieEDeHeiShou** [comment]
Am I bothering you yet?...For I open issues for two consecutive days...
Feel a little sorry for that...

**Comment by reteo** [comment]
You are polite and willing to help.  I never get tired of that.  If you were demanding, arrogant, and unwilling to do anything but be angry, on the other hand, I would find that rather tiring. ;)

**Comment by XieEDeHeiShou** [comment]
...Actually,I'm trying to localizate this mod .(The reason why I check codes...
I've asking for authorize on MC forum ...not get replied yet.I'm waiting and continuing my hard work
(I thought it should be easy,until  I accept your suggestion  and then have a look on those .xml files:)
No,not demanding,  nether arrogant :) 
By the way,Dartcraft not updated for long time,there still has its .xml in 1.7.10.jar
I can do little help to this mod,but just a little...
Well , not early for me now ,I'll go to sleep .May you have a nice day :)

**Comment by reteo** [comment]
I really should remove that thing; you're right, the most recent version of DartCraft is for 1.6
