### ISSUE TITLE
Something about those .xml file

### ISSUE THREAD

**Issue by XieEDeHeiShou** [lawremi/CustomOreGen#133]
I may keep this issue open for days until the moment I finished most of the localization work.
I'll post problems I found below this issue ,rather than add another .

1.I see a "-- Promethium Configuration UI Starting --" in Metallurgy4.xml ,while I cannot find this ore in Metallurgy4's .lang file ,but a similar word appears: tile.metallurgy.prometheum.ore.  Just one character not the same .
Are they mean the same material in game?

2.-- Ashtone Configuration UI Starting -- in NetherRocks.xml
   May be AshStone =-=?

3.In ReactorCraft:
-- Thorite Configuration UI Starting --    =   ore.thorium ?
-- Ammonium Chloride Configuration UI Starting --  =   ore.ammonium ?

4.In TC4.xml
-- Amber Bearing Stone Configuration UI Starting -- = tile.ore_amber ?

**Comment by lawremi** [comment]
These are all good catches, and your guesses are correct --- they all match. I think reteo will need to fix these in his ini files first, and then submit the regenerated configs. Thanks to both of you for your contributions.

**Comment by reteo** [comment]
Good catch with Prometheum and AshStone; those were indeed incorrect on my part.  However...

![Ammonium Chloride](http://i.imgur.com/Qqgtuvj.png)
![Thorite](http://i.imgur.com/RzgEI0j.png)
![Amber Bearing Stone](http://i.imgur.com/Qc1zHvo.png)

**Comment by lawremi** [comment]
Thanks for the fixes, reteo.

**Comment by XieEDeHeiShou** [comment]
Localization work complete.(CustomOreGen-1.7.10-1.2.24)

No more problem found.

**Comment by XieEDeHeiShou** [comment]
Wait,where is PFAA's xml file ?
Ok,I find it in PFAA's config ,but,why it's not like others in COG' config/modules?
I should told you this or I should told PFAA?

**Comment by lawremi** [comment]
What do you mean by it not being like the others? PFAA provides its own configuration.

**Comment by XieEDeHeiShou** [comment]
Eh...I mean COG support IC2,so there is a IC2.xml in COG's jar
And COG support PFAA,while there is not a PFAA's xml in COG's jar
I almost forget PFAA until I found it in modpack.
I've translated COG'xml but PFAA's.When I entered the game,tried to create a new world with COG,then I noticed PFAA' group (Of cause ,in English).
So,I was just suggesting if PFAA'xml should be in COG.jar (to make it more systemly I think).

**Comment by lawremi** [comment]
For mods that make direct use of COG, it would be too much trouble to coordinate distribution of their configurations. In particular, we would need to synchronize our releases, which would end up being infeasible as the number of dependent mods grew. 

But you're right that the translations would need to be distributed by the mod (PFAA), not COG, and that's not supported yet. Will see what I can do.

**Comment by XieEDeHeiShou** [comment]
Got it.
It seems that there is nothing I could post here anymore recently.
Maybe I'll be back next version or not :) 
Anyway, I'll close this issue now.

**Comment by XieEDeHeiShou** [comment]
Recently, a player asked me how to change the default options for ores' distributions.So I tried.
I add these to Clay' distribution(in COG.jar):
<Choice value='SparseVeins' displayValue='稀疏'>
                    <Description>
                        大型的，充填着少量矿物的矿脉。
                    </Description>
 </Choice>   (via the GUI,this worked.)
Then I close other ores' generation,just generate Clay (Ferq=2.0,Size=2.0) in a superflat world....
No Clay found .....

Then I delete what I add, and just change the original setting to 'SparseVeins'.
Worked in GUI, but not work in the superflat world....
Am I did something wrong?

So,the question is Can palyer change/add a generate distribution to an ore?
If yes,how to do it?

**Comment by lawremi** [comment]
Yes, of course you can add distributions. Modifying the jar is not the best way, but anyway, please show the actual XML that you added to define the clay distribution. It takes more than just an option. You might want to use Sprocket to do it.

**Comment by XieEDeHeiShou** [comment]
OK,thank you,  I'll have a look on Sprocket.

**Comment by XieEDeHeiShou** [comment]
Well,I tried with IC2's copper:
[Copper]
Distribution Presets: Layered Veins, Strategic Clouds, Vanilla, SparseVeins
Blocks: IC2:blockOreCopper

and then get this:
![qq 20160124221436](https://cloud.githubusercontent.com/assets/16363180/12536712/e3e5b80a-c2e7-11e5-91dd-093206e5f0b1.png)

but ... no copper found in the world.

Am I did something wrong?

Another question:
Can palyer add a new mod to COG by using Sprocket? (Create a similar ini file and then turn it into xml
....)

**Comment by reteo** [comment]
Found it.  While I don't have the Sprocket code, the XML shows that the distribution frequency is set to "0," meaning that 0 distributions will spawn per chunk.

> Another question:
> Can palyer add a new mod to COG by using Sprocket? (Create a similar ini file and then turn it into xml....)

Not only *can* they, but that was the reason Sprocket was created in the first place.  I've also gone to the trouble of studying other peoples' source codes to come up with the relative ore generation amounts to fit their mods' expectation of rarity.  I keep a spreadsheet available [here](https://github.com/reteo/Sprocket/blob/master/COG%20Ore%20Settings%20Chart.ods).

For example, [these](https://github.com/reteo/Sprocket/tree/master/configs/Examples/INI) are the Sprocket sources to [these](https://github.com/lawremi/CustomOreGen/tree/master/src/main/resources/config/modules) default configurations.
