### ISSUE TITLE
Detecting Creative Superflat

### ISSUE THREAD

**Issue by reteo** [lawremi/CustomOreGen#135]
Turns out that the mantle code can cause problems when using the default superflat world, since it gets covered in lava (being only 3 blocks high).  Is there a way to add superflat world detection to the XML spec?  The default configurations won't be affected by this, since they're off by default, but for Survival Industry, I have supplemental caves and mantle both enabled by default.

**Comment by lawremi** [comment]
Are they protected by `COGActive`? That should only be `true` when the `dimension.generator` is "RandomLevelSource" (as opposed to FlatLevelSource).

**Comment by reteo** [comment]
Sprocket uses "COGActive" for overworld ores, "HellLevelSource" for nether ores, and "EndLevelSource" for end ores.  Special Rules started life as a [Sprocket-generated file](https://github.com/reteo/Sprocket/blob/master/configs/Examples/Customized/Editing%20Demonstration/SpecialRules.xml), and was edited until it became the [final result](https://github.com/reteo/Survival-Industry/blob/master/config/CustomOreGen/modules/modpack/SpecialRules.xml)

**Comment by lawremi** [comment]
Do you see the special rules as particular to the overworld (and other overworld-like sources such as Mystcraft)? Or are they somehow more general?

**Comment by reteo** [comment]
I created the special rules to be specific to the overworld, specifically as a way to make some basic real-world effects happen (water table flooding, mantle level, igneous dikes, and, of course, huge caverns).  This is meant for the standard overworld, and Survival Industry is meant to be played in survival mods (hence the name).  I will admit, superflat worlds did not occur to me as a use case, but JeffPeng notified me of the edge case, so I thought I'd handle it before it became a general problem.

**Comment by lawremi** [comment]
Why not just wrap it in a check for `COGActive`?

**Comment by reteo** [comment]
[Run that one by me again?](https://github.com/reteo/Survival-Industry/blob/master/config/CustomOreGen/modules/modpack/SpecialRules.xml#L192)

**Comment by lawremi** [comment]
What is the value of `COGActive` in your world? Perhaps somewhere you have it set explicitly to `true`, so the default is not considered.

**Comment by reteo** [comment]
How is it set?  The modpack uses the vanilla default worldgen in order to keep latency down, and the only place COGActive is defined in the the defaults config, and I never changed it.

**Comment by lawremi** [comment]
Could be set in some options file. You can check using /cogOption in game to see how it is set. If it is somehow defaulting to true even for super-flat, that would be a bug. This obviously works with the Nether and End, so perhaps something is setting it based on the dimension ID being 0.

**Comment by reteo** [comment]
It's apparently active on a default superflat.

![Screenshot of default superflat with /COGOptionInfo COGActive](http://i.imgur.com/265H5LD.png)

**Comment by lawremi** [comment]
It turns out that the generator is "RandomLevelSource" by default, even when there is no world (like during the initial config load during world creation). The default evaluates to true, and then gets saved. The crux of the problem is that defaults are evaluated and saved before there is a world. I might make it so that invisible options are not saved during world creation.

**Comment by reteo** [comment]
Take your time.  There's a reason that "Survival" is in the name of the modpack. ;)
