### ISSUE TITLE
World Stuck on Pregen with Chromaticraft and CustomOre Gen

### ISSUE THREAD

**Issue by AuricPolaris** [lawremi/CustomOreGen#147]
While pregenning a Revolution 2 world with the WorldBorder plugin, the generation will get stuck and the CPU will max out with some sort of negative interaction between Chromaticraft and CustomOreGen.

Warmroast Profile: http://i.imgur.com/ZuPPcDg.png
KCauldron Version: KCauldron-1.7.10-1614.184 (Any higher versions will cause DragonAPI to hate KCauldron)
Mod's Disabled: Admin'sToolBox, Cyano'sLootableBodies, EnviroMine, FTBLib+FTBUtilities, and Roguelike dungeons.

(I have made a ticket [here](https://github.com/Haggle1996/RevolutionPack/issues/360) as well.)

Please let me know if you need any more information! :)

**Comment by lawremi** [comment]
I think this is an interaction with the Streams (farseek) mod, not chromaticraft. A comment on #146 also mentions Streams as a potential conflict. You might consider disabling it?

**Comment by AuricPolaris** [comment]
Hi lawremi,

Thank you for your above response. Upon removal of Streams and generating a new world we still see the same issue with Chromaticraft and CustomOreGen being the two mods consuming the entire CPU and not generating any more chunks. Image [here](http://imgur.com/3o9O7MY) of the CPU usage as described by warmroast:

**Comment by lawremi** [comment]
While Chromaticraft is showing up in the profile, it might be an innocent bystander. If you take it out, does the problem go away?
