### ISSUE TITLE
Multi-mod ore veins config not generating vanilla ores?

### ISSUE THREAD

**Issue by Nocty201** [lawremi/CustomOreGen#151]
Working on a custom pack for 1.7.10 using COG for ore generation; the idea is massive but infrequent deposits with OreFlowers to help locate them. So far, it's been going well...

But...

I can't seem to get the Vanilla ores to spawn properly with all the modded ores. I repurposed the vanilla.xml file, stripped out all the options I didn't want, and rewrote a lot of it to make it work. And it does work, quite well, for all the modded ores I've specified. The vanilla ores, well, I specified them but they simply don't appear to generate. I'm using an XRay mod to "see" the ore generation, but digging down to inspect manually also shows there is no vanilla ores.

I've tried disabling COG's generator (Vanilla MC spawned ores in vanilla distributions, but no giant clumps) and have double checked my XML (not that I understand it intuitively, so it might still have errors!).

The XML is http://pastebin.com/iiumYjRL - let me know if it's expired and I can update the latest version.

Here is an example of missing vanilla generation -> http://i.imgur.com/zfh7MCz.jpg

The Electrotine Ore should be part of a composite vertical pipe with Lapis and Redstone amongst it, while the Silver/Lead/Rose Gold at the bottom should have Vanilla Gold Ore with it. The lonely Osmium blocks on the top right should be nestled amongst Iron ore.

Here's examples of it working with distributions that don't include vanilla ores -> http://i.imgur.com/igz5oFD.jpg

The thaumcraft4 spikes have ores from "Tainted Magic" included in it, while the giant lump down below is a mix of Magneticraft Salt/Sulfur/Tungsten and Flaxbeard's Zinc.

A pure "vanilla" clump of Diamond inside Coal (based on the lava inside diamond option in the default configs) doesn't appear to spawn anything at all, but it's hard to prove a negative, of course.

The other thing that I'm not sure if I can point the finger at COG for is the occasional "lump" of glowstone or endstone that is appearing; about 5 blocks worth in a lump that's quite uncommon.

Happy to supply the pack if you need it for testing, I simply haven't sat down and checked all the permissions for redistribution yet so I don't want to put it up publicly (yet).

Thanks in advance for any help you can offer.

**Comment by reteo** [comment]
Did you edit the entire vanilla config by hand, or did you edit the Sprocket INI and edit the newly-generated file?

* [Sprocket INI](https://github.com/reteo/Sprocket/blob/master/configs/Examples/Standard/INI/VanillaMinecraft.ini) - This is actually the source of the default vanilla configuration, if it helps.

**Comment by lawremi** [comment]
My guess is that there is some other config replacing the vanilla ore blocks with stone. What does your `CustomOreGen_Config.xml` look like?

**Comment by Nocty201** [comment]
http://pastebin.com/8iDNL4ea - Customoregen_config.xml

http://pastebin.com/XUBCvUnR - updated ores.xml. It's based on the vanilla xml but rewritten/hacked by hand. I haven't used sprocket at all this time.

http://pastebin.com/pApBiT8Z - Thaumcraft4.xml, based almost entirely (if not is untouched from) reteo's work.

I'm going to go back through all the configs and mods in case I missed something in the meantime; will update here if I find my mistake.

Thank you both.

**Comment by lawremi** [comment]
You are importing the mod configs after your config, so the built-in Vanilla config will replace the vanilla ores with stone.

**Comment by Swandar** [comment]
Is a version that doesn't cut out the modded ores going to be available soon? I'm starting a minecraft series on youtube and I really want this mod.

**Comment by lawremi** [comment]
To what are you referring? This issue should probably be closed, since I'm pretty sure this was a bug in the custom configs.

**Comment by Nocty201** [comment]
Yes, it was a bug in my configs. Apologies for the confusion.
