### ISSUE TITLE
Multi-Thread ore generation

### ISSUE THREAD

**Issue by roboderpy** [lawremi/CustomOreGen#153]
Would be useful on multicore systems. Because CustomOreGen is very heavy to be done in main tick thread on world generation, i think COG should use multiple threads to generate veins.

**Comment by Draco18s** [comment]
Threading isn't that simple, sadly.

**Comment by lawremi** [comment]
COG will generate whenever the game tells it to. Minecraft is becoming more multithreaded, so we should expect this situation to improve.
