### ISSUE TITLE
World freeze.

### ISSUE THREAD

**Issue by DipsWW** [lawremi/CustomOreGen#154]
This issue happens when I add the mod to the Pickle Pack Magical 3 modpack created by BlakeBr0 that can be found on the curse launcher.

When I create a new world I dont change ore frequenct but I change ore deposit size to 5, and I disable Railcraft's Poor ores, Tinkers' Construct's Gravel ores and Chisel 2. When I load into the world everything works as its supposed to, the mod is working and I see ores all over the place as I wanted to. But after moving around for a few minutes the world freezes. TPS reaches 0 and stays that way forever. When exiting the world it freezes at "Shutting down internal server" and I have to use task manager to close it.

Not sure if theres any compatibility issues with any of the other mods Im using but I will include a list of all the mods further down.
Ive monitored task manager multiple times too see if it caps my processor or RAM but it never goes above 50% which is normal for me when playing modded minecraft. I have 6 out of 16 total gigs of RAM allocated to the game.
My specs are:
16GB DDR3 Memory RAM
980ti Gaming 6GB VRam
i7 4770 Intel Processor
The game is running on a 500Gig SSD

Mod List:
AE2 Stuff - bdew
AppleCore - squeek502
Applied Energistics 2 - AlgorithmX2
Aroma1997Core - Aroma1997
AromaBackup - Aroma1997
Automagy - Tuhljin
Bdlib - bdew
BiblioCraft - JDSinclair
BiblioCraft: BiblioWoods ExtraBiomes - JDSinclair
Blood Arsenal - Arcaratus
Blood Magic - WayofTime
Botania - Vaskii
Brandon's Core - brandon3055
Carpenter's Blocks - Syntaxial
ChickenChunks - chicken_bones
Chisel - tterrag1098
CodeChickenCore - chicken_bones
CoFH Core - TeamCoFH
CoFHLib - TeamCoFH
Custom Main Menu -  lumien231
DecoCraft2 - RazzleberryFox
Draconic Evolution - brandon3055
Ender Storage - chicken_bones
EnderCore - tterrag1098
Enhanced Inventories - ANIMENIAC7
Extra Utilities - RWTema
ExtrabiomesXL - Annysia
ExtraTiC - JeanGlassmaker
Fastcraft - Player
FastLeafDecay - Olafskii
Forbidden Magic - Assassinfox
Hardcore Ender Expansion - chylex
Hardcore Questing Mode - lorddusk
Hat Stand - iChun
Hats - iChun
Headcrumbs - ganymedes01
iChunUtil - iChun
Iguanas Tinker Tweaks - bonusboni
InGame Info XML - Lunatrius
INpureCore - INpreProjects
Inventory Tweaks - Kobata
JourneyMap - techbrew
LaunchGUI - TehNut
LookingGlass - XCompWiz
LunatriusCore - Lunatrius
Magical Crops Compat - Streuner91
Magical Crops: Armory - Mark719
Magical Crops: Core - Mark719
Magical Crops: Decorative - Mark719
Mantle - mDiyo
Minefactory Reloaded - skyboy026
MineTweaker3 - StanH
ModTweaker- jaredlll08
Morpheus - Quetzi
Mouse Tweaks - YaLTeR97
MPUtils - GenDethrow
Mystcraft - XCompWiz
NEI Integration - tonius111
NetherOres - skyboy026
NotEnoughItems - chicken_bones
NotEnoughResources - Way2muchnoise
OpenBlocks - OpenMods
OpenModsLib - OpenMods
PickleTweaks - BlakeBr0
ProjectE - sinkillerj
Railcraft - CovertJaguar
Reliquary - x3n0ph0b3
Resource Loader - lumien231
Roguelike Dungeons - Greymerk
Runic Dungeons - MrComputerGhost
SimpleLabels - insaneau
Solar Expansion - TedTheRusSB624
Soul Shards: The Old Ways - SgtPunishment
StartingInventory - bskprs
Storage Drawers - jaquadro
Storage Drawers: Misc Pack - jaquadro
Thaumcraft - azanor
Thaumcraft Inventory Scanning - Blay09
Thaumcraft NEI Plugin - DjGiannuzz
Thaumcraft Node Tracker - Dyonovan
Thaumic Energistics - Nividica
Thaumic Horizons - TheKentington
Thaumic Tinkerer - nekosune
The Twilight Forest - Benimatic
Thermal Dynamics - TeamCoFH
Thermal Expansion - TeamCoFH
Thermal Foundation - TeamCoFH
TiC Tooltips - squeek502
TiConAutoToolStation - Blubberbub
Tinkers Construct - mDiyo
Torcherino - sci4me
Waila - ProfMobius
Waila Harvestability - squeek502
Waila Plugins - tterrag1098
Wireless Redstone - chicken_bones
Ztones - riciJak
CustomOreGen - lawremi

**Comment by Harkole** [comment]
I've recreated this with a much smaller custom mod pack:

CustomOreGen (1.4.2)
Harder Farming
Harder Ores
HardLIb
JourneyMap
JEI
JEI ToolTips
Ore Flowers
WAILA
WAILA Harvestability
WAWLA

**Comment by lawremi** [comment]
Do you have to do anything special to cause the freeze? Or just load a world and wander around for a while? Could you try to reproduce it with an even smaller set, say including only Harder Ores and/or Ore Flowers?

**Comment by Harkole** [comment]
Apologies been ill so only just catching up with things, I'll attempt to re-create although it maybe related to wireframe/debugging options.

I had turned them on then quit out of the world, going back in caused the game world to be frozen (pigs/chickens wouldn't move although wings were flapping) and no new chunks would generate.

I'll put together a pack with just the basics and nothing else and update, but it'll be about 9-10 hours from now when I finish work.

**Comment by Harkole** [comment]
Further testing reveals this is actually the wire frame debug issue, if you crash out the world then change the config options when you load the world the wire frames are missing but the world is frozen
