### ISSUE TITLE
Odd Crash

### ISSUE THREAD

**Issue by Draco18s** [lawremi/CustomOreGen#157]
I was in the middle of working on some loot table modification code when suddenly COG decided it didn't like something and vomited this at me:

http://pastebin.com/geujib0t

I have no idea what's wrong. I haven't touched COG or any COG config files in weeks and I had the game running fine an hour ago, even commented out the method I'd been writing (which worked partially an hour ago) and it still crashes.

**Comment by Draco18s** [comment]
Nevermind, I know what I did.
I was fiddling around with lambda and that made my project jump to 1.8 compliance, and *THAT* broke COG.

**Comment by lawremi** [comment]
Weird. I ported to 1.10.2 using 1.8 compliance and haven't had any issues. Looking at the error, there's little chance this is a bug in the COG source code, so I'm going to close this. If we find a way to reproduce it, we can reopen.

**Comment by Draco18s** [comment]
Yeah, I dunno. I can get it to happen by switching Eclipse to 1.8 again, but that's all I know.
