### ISSUE TITLE
v1.4.1 - Crash after going to More Options after setting up New World custom ore gen.

### ISSUE THREAD

**Issue by Rensik** [lawremi/CustomOreGen#159]
Crash Report
http://pastebin.com/jPnv0BXq

**Comment by SirChamomile** [comment]
I'm getting this too whenever I hit any button on that screen except Custom Ore Gen and Create World.
[crash-2016-11-03_16.05.52-client.txt](https://github.com/lawremi/CustomOreGen/files/570184/crash-2016-11-03_16.05.52-client.txt)

**Comment by lawremi** [comment]
I will look into this tonight. It sounds like it's depending on a deobfuscation mapping that does not exist in Forge/FML yet.

**Comment by SirChamomile** [comment]
Still getting this crash if I generate a world, exit the world, and then go to a new world creation screen and try to click the More Options button.

**Comment by lawremi** [comment]
It's unlikely to be the same error, since the code does not reference that field by name at all anymore. Are you sure it's the same crash log?

**Comment by SirChamomile** [comment]
This is the bug I've gotten, I guess maybe it just seems similar:

[crash-2016-11-07_22.16.10-client.txt](https://github.com/lawremi/CustomOreGen/files/577354/crash-2016-11-07_22.16.10-client.txt)

**Comment by lawremi** [comment]
This is a duplicate of #163. The original issue was resolved, so closing.
