### ISSUE TITLE
Custom Ore Gen breaking vanilla terrain generation?

### ISSUE THREAD

**Issue by SirChamomile** [lawremi/CustomOreGen#160]
When I was able to bypass the crashing at the loading screen (#159), I couldn't get into the world without it crashing when run with Better Foliage:

[crash-2016-11-03_17.27.52-server.txt](https://github.com/lawremi/CustomOreGen/files/570247/crash-2016-11-03_17.27.52-server.txt)

Loading up the world without Better Foliage, it seems like biome decoration might be broken:

![2016-11-03_17 39 52](https://cloud.githubusercontent.com/assets/23204608/19988573/d57e2220-a1ee-11e6-8824-451a65694f9b.jpg)

This should have used the default generation setting as I couldn't actually access generation options. I do have RTG/CC/BOP installed though.

**Comment by lawremi** [comment]
It looks like you also have optifine installed. Could you please try without that?

**Comment by SirChamomile** [comment]
I'm still getting #159, but I'm not having better foliage crash any longer after removing Optifine. It's curious though as this does not happen without the presence of CustomOreGen.

**Comment by lawremi** [comment]
I think there is some multi-threaded world generation happening with optifine, and since COG is doing so much of it, crashes become more likely. Closing for now since there is no obvious next action.

**Comment by SirChamomile** [comment]
I'm still crashing with Better Foliage, but I was able to avoid the conflict between Optifine and COG by tinkering with the settings in Optifine. I believe the culprit is the Smooth World function within Optifine.
