### ISSUE TITLE
Readme.md points to the ShoutWiki, calling it current, while it does not appear to have been updated since 2013

### ISSUE THREAD

**Issue by belathus** [lawremi/CustomOreGen#161]
There is still a large amount of information there, but a lot of it is not remotely up to date.

If you don't mind, I could edit the wiki on this github to add a lot of the information I'm finding useful. IE, the generator class stuff that reteo posted about on the Minecraft Forum back in January.

**Comment by lawremi** [comment]
Sure, that sounds great. I think anyone can edit the GH wiki.
