### ISSUE TITLE
Alternate Terrain Generation (ATG) support.

### ISSUE THREAD

**Issue by Timorr** [lawremi/CustomOreGen#165]
Somehow, the Custom Ore Generation settings aren't applied to ATG worlds in 1.7.10. I tested it with different settings, and nothing changed in the ore generation. I thought these two mods where compatible, but they don't seem to work together well... I am using version 1.2.26 with forge 10.13.4.1558.

**Comment by lawremi** [comment]
First time I've heard this is not working. Are you using the debugging wireframes? Are you sure there's no error in the log?

**Comment by Timorr** [comment]
Nope. But with any other type than "vanilla" generation, it works (veins, layers, clouds, etc).
Somehow vanilla gen is broken. Tried it in vanilla worlds too, and it did the same.

**Comment by lawremi** [comment]
Which "settings" are not having an effect?

**Comment by Timorr** [comment]
The "vanilla" deposit setting.

**Comment by reteo** [comment]
Right, but what is "Vanilla" doing (or not doing)?  Are you not seeing any ore spawn?  Are you seeing too little?  Too much?  Or are you simply seeing the original ore spawning practices?

**Comment by Timorr** [comment]
I looks like my size and frequency settings aren't being applied. Set them to X5.00 both, and the ore was spawning using regular X1.00 settings.

**Comment by reteo** [comment]
Ah, so the problem is that the main sliders aren't having an effect on the vanilla generation?
