### ISSUE TITLE
No AE2 quartz in 1.10

### ISSUE THREAD

**Issue by Baughn** [lawremi/CustomOreGen#166]
AE2 is detected, but the generation option doesn't want to switch from "no".

Probably the block names changed. I expect I'll update this with a solution later today, just wanted to mention the problem.

**Comment by lawremi** [comment]
See #156. I've figured out a lot of the new block IDs. Just need to regenerate the XML files.

**Comment by Baughn** [comment]
How do you generate those XML files in the first place?

I've always edited them manually, which is a pain. I just looked, and there's nothing obvious in the repository; in fact, if they're generated, I would have expected build.gradle to have an updateXmlConfiguration task or something.

If you tell me how, I'll send you a PR to implement that. :)

**Comment by lawremi** [comment]
@reteo has been contributing built-in XML files that he generates using his "Sprocket" tool. See: https://github.com/reteo/Sprocket.

**Comment by Baughn** [comment]
For reference, the ores are <appliedenergistics2:quartz_ore> and <appliedenergistics2:charged_quartz_ore>

**Comment by lawremi** [comment]
Shoul be fixed by reteo's #169.
