### ISSUE TITLE
Can you do your mod more easier or write new lite version

### ISSUE THREAD

**Issue by BurovB** [lawremi/CustomOreGen#183]
Custom Ore Gen is very interesting mod which help very much customize your modpacks. For example now, I create TerraFirmaCraft+GregTech modpack, but I can't use cog because it's to hard. I know that this mod have wiki but cog is hard enough and wiki isn't very clear. Create please lite version of this mod, for example, it doesn't have custom gui and all configuration are in config file. You can disable vanilla ores and ores from mod and for example something like this (config file):
********************
VeinName(###)
Biomes:###^#, #####^#
Ore:###^#, ###^#
Height:###^###
VHeight:###
Area:##
Mass:###
Density:###
********************

********************
VeinName(GalenaOre)
Biomes: ExtremeHills^60, Forest^40
Ore: Galena^70, Antimony^30
Height: 40^80
VHeight:8
Area:3
Mass:40
Density:2
********************
What this means? This means that in world will be generated ore vein with name “GalenaOre” with frequency 40/(40+n)*100%(“n” is mass of other veins). It will be spawn in biome ExtremeHills with frequency 60% or Forest with frequency 40%. It will be comprise 70% of Galena ore and 30% of Antimony ore (users must write in this pole id of some ores). It will be spawn on height 40-80(with the biggest frequency in the middle). Height of this vein in blocks is 8 and it will spawn on area 3^3. His density will be 2 blocks of ore per one block of cobble. All veins are cubic.

**Comment by lawremi** [comment]
You are looking for Sprocket. https://github.com/reteo/Sprocket

**Comment by reteo** [comment]
Maybe.  Note that GregTech was mentioned.  Sprocket doesn't support NBT tags, so GT ores will not be configurable using the utility.

**Comment by BurovB** [comment]
> Maybe. Note that GregTech was mentioned. Sprocket doesn't support NBT tags, so GT ores will not be configurable using the utility.

This meanes that maybe you can do lite version of cog?

**Comment by lawremi** [comment]
It means someone could improve Sprocket.

**Comment by reteo** [comment]
It's open to whoever wants to fork it.

**Comment by BurovB** [comment]
Maybe still do it?( Without gui and variability, if user must do setting by the template it isn't very hard to write. In addition no one know how user must work with it(sprocket). I'm write to sprocket owner, but it will be better if you do it.

**Comment by reteo** [comment]
I am the maker of Sprocket, but I've retired from it.  It's in the GPL, so anyone is free to fork it and make their own version.

**Comment by BurovB** [comment]
So, to how I must write?

**Comment by reteo** [comment]
The instructions are on the Sprocket main page, under the file list.

**Comment by BurovB** [comment]
I do not speak englich well enough and I don't now how use pyrhon(

**Comment by reteo** [comment]
I'm afraid I can't help you, then.  Have you tried running it through Google Translate?

**Comment by BurovB** [comment]
I know about translate, but it's very "crooked". Maybe it's can do like a fork cog owner?

**Comment by lawremi** [comment]
Maybe at least post the NBT limitation as an issue on the Sprocket repo and if/when someone forks it, that person can decide to address it. Eventually, I'll have to fork it to get things working a bit better on recent versions of Minecraft (but I am personally sticking with 1.7.10 for now).

**Comment by reteo** [comment]
Well, I've added an issue, as well as a note in the documentation that NBT isn't supported.

**Comment by BurovB** [comment]
Ok, thanks for very good support. Maybe when it makes sense to write this mod, but if you'll just write(in the near future), make it for version 1.7.10.

**Comment by BurovB** [comment]
If you will do it write me on email.
