### ISSUE TITLE
GregTech 5U Generating Disabled Ores

### ISSUE THREAD

**Issue by Rongmario** [lawremi/CustomOreGen#184]
I haven't found any more but upon worldgen I stumped upon this Mirabilite/Realgar/Gypsum/Borax/Salt/RockSalt mix vein, but only the salt and rocksalt ore has recipes so I assume other ores are disabled by default, anyway of seeing what causes this or how to enable it in GT configs to do things with them?

![2017-01-29_01 59 58](https://cloud.githubusercontent.com/assets/3684700/22401367/30a07fb4-e5c8-11e6-8b92-f569e91504a2.png)

**Comment by lawremi** [comment]
I guess there's always the Gregtech MineTweaker addon. And the unreleased stuff in PFAA I'm working on (very actively but it's slow going).

**Comment by Rongmario** [comment]
Can you further expand your point? What would the MTAddon do?

**Comment by lawremi** [comment]
You could use it to add recipes to do stuff with the ores.

**Comment by Rongmario** [comment]
Thats what I'm planning to do, seems like GT does add recipes for its dust variant already.
