### ISSUE TITLE
Incompatibility with Biomes o Plenty

### ISSUE THREAD

**Issue by shnorb** [lawremi/CustomOreGen#186]
The game crashed whilst updating screen events
Error: java.lang.NullPointerException: Updating screen events

Sorry cant access the log. Some issue with my OS unrelated. Am certain that these two mods are incompatible. Can boot into a game if Biomes o plenty isnt used to create the world. But when it is used, the game slows and crashes a few minutes in. Using latest build of Customoregen, mc 1.10.2 and latest biomes 1.10.2 build.

**Comment by lawremi** [comment]
Were you using the debugging wireframes? There is a bug that is fixed in git, just need to release the fix.

**Comment by lawremi** [comment]
Probably improved in latest release, with a real fix in the next release..
