### ISSUE TITLE
Not seeing all ore gen mods in the GUI at world creation screen (1.10.2)

### ISSUE THREAD

**Issue by tachometer74** [lawremi/CustomOreGen#187]
I have the following ore generation mods in my custom mod pack:
-Biomes O' Plenty 5.0.0.2155
-Forestry 2.2.1.103
-Immersive Engineering 0.10-57
-Project Red 4.8.0.17

When I click on "Create New World" and "Custom Ore Generation" I only see BOP on the list.

I do see XML files for all of those mods in the config > CustomOreGen > modules > default.

I tried two versions of CustomOreGen (1.4.2 & 1.4.1) and had the same results.

All config files are stock.

**Comment by lawremi** [comment]
See #156. We need to update the configs to support the different mods.
