### ISSUE TITLE
[Lag]: Slow Worldgeneration /w CustomOreGen[COG]

### ISSUE THREAD

**Issue by Lanse505** [lawremi/CustomOreGen#190]
**Version in Use:**
Minecraft:  1.10.2
Forge:        12.18.3.2254
COG:          1.10.2-1.4.2

Hello!

I've recently done a bit of debugging to fix the world generation slowness in mine as well as a few other packs. During my investigations (using Jprofiler), I've found some common culprits, COG being one of them it seems. We're talking a heavy enough hit for it to take a few minutes to load up and be able to do anything in a new world.

Pictures from JProfiler:
http://i.imgur.com/0H1iK6G.png
http://i.imgur.com/ZoDnw7i.png
http://i.imgur.com/T3N0RAZ.png
http://i.imgur.com/MsCYm07.png

The two most active hotspots seem to be; 
"CustomOreGen.Server.MapGenDistributor.getCashedStructureGroup" & "CustomOreGen.Util.HeightScaledPDist.scale".

Also, it seems to be calling an ungodly amount of "blockpos" checks, about 100-200k checks every 1 to 2 seconds during initial world generation from my testing. 

If you'd like I can provide a profiler snapshot also for further digging.
//Best Regards 
Lanse505

**Comment by lawremi** [comment]
COG just does a lot of generation. I don't think there's any way to speed up `getCachedStructureGroup()`, which is just hitting a hash map. The `scale()` method is just a simple multiplication and two getter calls that are almost always trivial. I guess some optimization is possible there, but somehow limiting the number of distributions would bring much bigger savings.

**Comment by lawremi** [comment]
Sorry, I don't plan on addressing this. You might consider pregenerating a world to avoid the performance hit.
