### ISSUE TITLE
Wire-frame debug crashing often. 

### ISSUE THREAD

**Issue by Claycorp** [lawremi/CustomOreGen#191]
https://pastebin.com/wsJTRLWf
https://pastebin.com/yQC7j4zW
https://pastebin.com/Un5A9nS9

Its making it near impossible to test the orgen. If you know any other way to do so it would be nice to know of as currently the mod isn't use-able with no way to test the settings you have.

**Comment by lawremi** [comment]
Fixed in github. Just need to release it.

**Comment by Claycorp** [comment]
Its been 5 months from the last push... Why has it taken this long to get a new build out? It's obviously not be worked on.

**Comment by lawremi** [comment]
That's true.

**Comment by Claycorp** [comment]
So I take you aren't interested in pushing the version on git?

**Comment by lawremi** [comment]
It is pushed onto git. I wanted to get a few things (like mod support)  done before releasing on curseforge. But I guess those things are not going to happen soon.

**Comment by Claycorp** [comment]
If you don't plan on adding the extra support soon can you just put up a fixed build please... I would prefer to use the mod and finish the configs I have rather than scrap it and switch to something else.

**Comment by lawremi** [comment]
Just uploaded 1.2.27, please let me know if there are still issues.

**Comment by Claycorp** [comment]
I will test it tomorrow when I work on it next. Thank you SOOOOOO much!
