### ISSUE TITLE
COG using wrong chisel block for generation.

### ISSUE THREAD

**Issue by Scratchman** [lawremi/CustomOreGen#192]
Using your latest version, CustomOreGen-1.10.2-1.2.27.jar, I've noticed that COG is using the wrong chisel2 blocks for generation.

The chisel 2 mod uses it's raw chisel blocks, like raw marble, for world generation but COG is using the cracked version of chisels blocks for it's strata world generation, and instead of COG replacing Chisels world generation both COG and Chisel are generating chisels blocks.

Thanks for the mod update, I was really hoping we would be able to use it in 1.10.2.

**Comment by lawremi** [comment]
What's the metadata value for the raw blocks in your version? From this [code](https://github.com/Chisel-Team/Chisel) it looks like it might be 7.

**Comment by Scratchman** [comment]
I think you're right, it's 7.

Pic of COG gen beside chisel gen .. https://www.dropbox.com/s/g41txe7mu7eg8cp/2017-05-11_14.07.58.png

**Comment by lawremi** [comment]
Ok, this should be fixed in next release. Thanks!

**Comment by Scratchman** [comment]
So close, but not quite.

Now COG is using the Big Tile block for generation, instead of the raw blocks.

http://imgur.com/a/Zlyhy

**Comment by lawremi** [comment]
Just pushed 1.4.4 which cleans up the chisel generation. Stripped it down to limestone and marble and added basalt (disabled by default because Chisel treats it specially by default).
