### ISSUE TITLE
feature request: alpha release for mc 1.12 on curse

### ISSUE THREAD

**Issue by mvdhoning** [lawremi/CustomOreGen#202]
Draco18s made an 'unoffical' version of your custom ore gen mod. That versions seems to just work fine on 1.12. Unfortunately a modpack containing the 1.12 build from Draco18s is not accepted at curse.
When will you be able to take up on his pull request and do an official 1.12 release at curse?

**Comment by lawremi** [comment]
Please let's just keep this on the pull request issue.
