### ISSUE TITLE
Draco's 1.12 version Compatibility with Open Terrain Generator?

### ISSUE THREAD

**Issue by Guinaro** [lawremi/CustomOreGen#205]
Currently I have troubles getting COG to generate ores when using Open Terrain Generator.
I'm using the unofficial 1.12 version of Draco on a 1.12.2 Minecraft.
Forge: 14.23.2.2618
COG: 1.12 Draco unofficial
OTG: 1.12.2 v5
I really would love to be able to use both at the same time. As both mods provide a lot of control in generating a nice minecraft world.
CoFH World does work for oregeneration, but doesn't offer the same functionality as COG.
Would it possible to look into the issue why COG and OTG don't work together?
Or maybe give insight in what I might be doing wrong?

Thank you,
Guinaro

**Comment by lawremi** [comment]
I'm guessing it's just the configs conditioning on a particular set of world generators (in order to avoid generating outside of non-overworld-style dimensions). Just customize the configs as documented and see if that works.

**Comment by Guinaro** [comment]
I use only three mods to test: OTG, COG and worldstripper.
I use the following XML files: CustomOreGen_Config.xml https://pastebin.com/Tpq6frPp
And following 2 xml files placed in the Modules/Custom Folder:
COG ModPack Main.xml https://pastebin.com/3eD01P2T
COG ModPack Generation.xml https://pastebin.com/1ArZf2XH
All default files are disabled (resulting in a LOG warning of a not found null option, which I traced down to a value set by the vanilla.xml (but doesn't hinder the working of COG).

If I run either mod seperately they properly do their thing.
If I combine them, I have no ores at all.
I am forcing COG to run in a way, that I force it to activate without checking for specific world generators, aswell as no checks whatsoever for generation. The XML files provide a Cloud like long swirl of Coal intermixed with a 1% chance of diamond ore.
Furthermore I force OTG to only generate one ore in a limited version that generates plains only (together with beach, ocean and river) and only iron_ore.
So when running: I get for OTG iron ores, for COG coal/diamondores. Together nothing.
If you want I can send you a zip file with my config setup for a MultiMC instance. 
I really would like this solved, however I lack the skills to go code hunting and find out where it goes wrong. 
Thanks,
Guinaro

**Comment by lawremi** [comment]
If you use debugging, do you see the wireframes? If not, the distributions are not loading for some reason. There might be an error in the logs. If they do show up, but just aren't populating, then something weird is happening.

**Comment by Guinaro** [comment]
No when enabling debug wireframes, they are not showing up. Only a green grid, but not the coal ore distributions grey wireframes. 
When running seperate COG creates a filled CustomOreGen_Options.txt files both on the Global Saves level aswell on the DIM levels. If running with OTG: CustomOreGen_Options.txt generates also on both global and DIM, but only the DIM versions have actually values entered.
Thus the global world has
#Custom Ore Gen @VERSION@ Config Options
#Mon Feb 26 21:00:04 CET 2018

And the DIM-0 has
#Custom Ore Gen @VERSION@ Config Options
#Mon Feb 26 21:00:04 CET 2018
COGActive=true
oreFreq=1.0
oreSize=1.0
debugMode=false
deferredPopulationRange=16.0
drawWireframes=true
debugDist=false
advOptions=false
enableMPCOG=true
enableCoalOre=true
vnlaCoalFreq=1.0
vnlaCoalSize=1.0

Running seperate DIM0 is the same and World version has
#Custom Ore Gen @VERSION@ Config Options
#Mon Feb 26 20:46:49 CET 2018
oreFreq=1.0
oreSize=1.0
debugMode=false
advOptions=false
enableMPCOG=true
enableMPCOGVanillaCleanup=false
enableCoalOre=true

 I think it has something to do, with the fact that OTG is probably operating differently then other worldproviders. The strange thing is, that CoFHWorld does work with OTG. But I do get the impression that CoFHWorld works on a single chunk base, and COG generates stuff across multiple chunks.

Guinaro

**Comment by lawremi** [comment]
Please try using the debug commands to figure out why the distributions are not loading. There might also be a stacktrace in the log where it encounters an error in the processing. The difference in options files is interesting, but I don't see anything wrong with either of them.

**Comment by Guinaro** [comment]
Here is a Gist with an overview of the COG XML files used. Aswell as minecraft Logs, from a run with COG and OTG enabled, COG Running alone and OTG Running Alone.
https://gist.github.com/Guinaro/53d0ffcbdf28f5586af8f58d85060db3
Here are also some screenshots of the world when just created with Debug of COG on.
OTG And COG Together (No ores generated from nor Cog nor OTG)
![2018-03-11_21 02 27](https://user-images.githubusercontent.com/16608305/37258041-f94ea3a2-2571-11e8-8f05-3d24a53c003d.png)

COG Alone (Sparse cluster of Coal Ore)
![2018-03-11_21 11 14](https://user-images.githubusercontent.com/16608305/37258044-00a53f62-2572-11e8-8e16-5a14aa7c1efe.png)

OTG Alone (some iron ore near the bottom)
![2018-03-11_21 08 17](https://user-images.githubusercontent.com/16608305/37258047-0bb5964a-2572-11e8-8c77-a83334f2ac9d.png)

As you see when running together no ores are created
I have used the /cogEnableDebugging command and /cogReloadConfig. But no wireframes show up.
If you want me to run specific tests or commands, please specify what needs to be done, enable where, ... and will gladly test out.

**Comment by lawremi** [comment]
Thanks. I was thinking you might run `/cogInfo .*`  to get a list of loaded distributions, with their settings. If the coal distribution shows up, we can figure out why it isn't being generated (like the wrong biome or something).

**Comment by Guinaro** [comment]
With both COG and OTG running I get after /cogEnableDebugging and running /cogInfo .* following output in Minecraft.log

```
[08:13:28] [Server thread/INFO] [customoregen]: Loading config data for dimension 'C:\Games\Minecraft\MultiMC\instances\1.12.2 debugging COG and OTG\.minecraft\saves\Modpack World\DIM0' ...
[08:13:28] [Netty Local Client IO #0/INFO]: [CHAT] Changed 1 options for C:\Games\Minecraft\MultiMC\instances\1.12.2 debugging COG and OTG\.minecraft\saves\Modpack World\DIM0
[08:13:33] [Server thread/INFO] [customoregen]: Custom Ore Gen @VERSION@ (Dim 0, 1/1 distributions):
 vnlaCoalVeins
[08:13:33] [Netty Local Client IO #0/INFO]: [CHAT] Custom Ore Gen @VERSION@ (Dim 0, 1/1 distributions):
[08:13:33] [Netty Local Client IO #0/INFO]: [CHAT]  vnlaCoalVeins
```

So the distribution seems indeed loaded, however not generating.
In my config, nor generation xml I specify limits on biomes. So I would assume that this vnlaCoalVeins distribution would generate in any biome.

**Comment by Guinaro** [comment]
Somehow OTG 1.12.2 v6 solved the issue of COG not being able to generate ores.
