### ISSUE TITLE
Default vanilla.xml gives false info on vanilla ore generation setting.

### ISSUE THREAD

**Issue by Guinaro** [lawremi/CustomOreGen#206]
When testing the issue with OTG and COG not generating ores. I was mislead by the following in vanilla.xml

```
    <OptionChoice name='vanillaOreGen' displayName='Allow Vanilla Ore Generation?' default=':= !?enableVanilla' displayState='hidden' displayGroup='vanillaHiddenAssignments'>
      <Description> Should Custom Ore Generation handle Vanilla ore generation? </Description>
      <Choice value=':= ?true' displayValue='Yes' description='Keep the vanilla oregen disabled.'/>
      <Choice value=':= ?false' displayValue='No' description='Vanilla ores will be handled by Minecraft directly.'/>
    </OptionChoice>
```

Since description for false says Vanilla ores will be handled by Minecraft directly I have always had it set to false, so that all ores could be generated. However I should have followed the DisplayName.
As setting it to false, disables vanilla oregen, thus also the oregeneration provided by e.g. OTG. That was the reason that with OTG 1.12.2 v6 and still wasn't seeing ores, while COG did generate ores. When switching the setting of vanillaOreGen to true. The ores from OTG appeared aswell.

So alter vanilla.xml to:
```
    <OptionChoice name='vanillaOreGen' displayName='Allow Vanilla Ore Generation?' default=':= !?enableVanilla' displayState='hidden' displayGroup='vanillaHiddenAssignments'>
      <Description> Should Custom Ore Generation handle Vanilla ore generation? </Description>
      <Choice value=':= ?true' displayValue='Yes' description='Vanilla ores will be handled by Minecraft directly.'/>
      <Choice value=':= ?false' displayValue='No' description='Disable the vanilla oregeneration.'/>
    </OptionChoice>
```
I haven't tested this with the v5 of OTG, as the issue of no COG oregen was fixed with v6 and I continued trying to find what was wrong.

Guinaro

**Comment by lawremi** [comment]
Thanks for this. Of course, it's best to avoid configuring this internal option directly.

**Comment by Guinaro** [comment]
The trouble is that OTG forces your hand to do everything directly into scripts as you do not get to see a COG configuration menu. So I simply had to. Sorry it took so long to check this parameter.
