### ISSUE TITLE
The Lost City compatibility

### ISSUE THREAD

**Issue by LiaungYip** [lawremi/CustomOreGen#209]
With the default configuration, Custom Ore Gen generates nothing in "The Lost City" dimensions.

That can be fixed by adding `LostCityChunkGenerator` to the list of `ChunkProviders` in `CustomOreGen_Config.xml`:

        <OptionChoice name='COGActive'
                      default=':= dimension.generator.class = "ChunkProviderOverworld" | dimension.generator.class = "ATGChunkProvider" | dimension.generator.class = "ChunkProviderRTG" | dimension.generator.class = "LostCityChunkGenerator"'
                      displayGroup='groupInternal'>
            <Choice value='true' displayValue='On'/>
            <Choice value='false' displayValue='Off'/>
            <Comment>
              Controls whether COG is active in the current
              dimension. Copy this file to CustomOreGen_Config.xml and
              modify the expression for the default value to control
              where COG is active by default.
            </Comment>
        </OptionChoice>

This should be incorporated into the default configuration.

**Comment by lawremi** [comment]
The configuration has not looked like that since 1.7.10, and the Lost Cities mod is for 1.10.2 or later, so I am a little confused.

**Comment by LiaungYip** [comment]
It sounds like I've managed to duplicate #177.

I got this configuration from the 1.12 version of the mod maintained by draco18s - https://github.com/Draco18s/CustomOreGen/tree/1.12/jars .

I'm guessing that the main problem is that Draco18s' fork is 94 commits behind master, so it ships a very stale config file.

**Comment by lawremi** [comment]
Yea, the 1.12 port by Draco has a ton of conflicts. I will need to work through those and get this updated to 1.12. Closing this since it's essentially obsolete.

**Comment by LiaungYip** [comment]
No problem.

I'm finally catching up on the work I was doing on Sprocket some months ago - I'll probably have something to show for that effort soon. So don't worry too much about config updates for 1.12 - I will be helping in that space.

**Comment by lawremi** [comment]
Great to hear that someone might be taking on the Sprocket ini maintenance. For now I might just hack the configs as needed just to make things work.
