### ISSUE TITLE
Please please please release to curse for 1.12

### ISSUE THREAD

**Issue by Shovinus** [lawremi/CustomOreGen#212]
I have a mod pack in 1.10 using your ore gen, and its such a nice experience to mine in. However 1.10 is a bit old and major mods that would improve on the feel of the pack are in 1.12, but without your ore gen it is pointless to move it to 1.12

**Comment by lawremi** [comment]
Just uploaded it. Minimal testing.

**Comment by Shovinus** [comment]
Legend <3
