### ISSUE TITLE
Return to title screen bug

### ISSUE THREAD

**Issue by Nemerensis** [lawremi/CustomOreGen#213]
Version: CustomOreGen 1.12-1.8.0

After setting the config to handle vanilla gen and setting iron and coal to "none" in the custom ore gen gui during world creation followed by clicking create world I am returned to the title screen.

There is no hard crash and nothing gets added to the log or debug log as a result of attempting to generate in this way.

Edit:
This may be an issue with the vanilla config imported via CustomOreGen_Config_Default.xml or with changes made in the gui when no CustomOreGen_Config.xml is copied/created from the default.  More testing will be needed.
Edit 2:
This might also be due to creating a world, exiting the world, and creating another with different settings.  This also causes all settings to reset to the CustomOreGen_Config.xml after clicking exit to desktop (maybe an intended behavior?) when attempting to reload the client after this bug.

**Comment by lawremi** [comment]
Is there a sure way to reproduce this, or does it happen randomly? I haven't observed this behavior.

**Comment by JaguarM** [comment]
The bug actually happens if you change any cog setting.
