### ISSUE TITLE
Log spam/loading config for every new chunk

### ISSUE THREAD

**Issue by Nemerensis** [lawremi/CustomOreGen#215]
![image](https://user-images.githubusercontent.com/38839287/40891395-5a80a70a-674a-11e8-8e89-b90143a7aa58.png)

**Comment by lawremi** [comment]
What are the steps to reproduce?

**Comment by Nemerensis** [comment]
Sorry for the delay, had a busy month at work and now I'm having trouble reproducing it. I'm not sure if an update or some other weird condition existed at the time I reported this but I cannot seem to reproduce it anymore.
