### ISSUE TITLE
COG is causing a NPE with lost citie's debug command

### ISSUE THREAD

**Issue by wormzjl** [lawremi/CustomOreGen#216]
After installing COG, whenever I tries to use /lc_debug command from the lost cities mod it gives a NPE in the console, could you take a look at this issue? Since commands in this mod are very helpful in debugging generations.
Full log with the error in the end: https://gist.github.com/wormzjl/1f273d3ecb0062e5512ec4c3a91e102c

Source of the lost cities mod: https://github.com/McJtyMods/LostCities

**Comment by lawremi** [comment]
Have you raised this with the Lost Cities developers? The crash is obviously in their code, so even if the bug is in COG, they might help with the diagnosis. I glanced at the indicated code, but the cause wasn't obvious.
