### ISSUE TITLE
Placing any xml file in the custom directory stops CustomOreGen from working

### ISSUE THREAD

**Issue by JaguarM** [lawremi/CustomOreGen#217]
If you place a file with an ".xml" ending in the \config\CustomOreGen\modules\custom directory and the mod will stop working. The error occurs with different or no text  in the file, mod Versions or Forge versions. It prevents the ore generation, the /cofEnableDebugging command (Error NULL) and the ore options screen from working.

The following will be of topic but I really like this mod. I have been looking at this github page for quiet some time because I will be making a small but game changing modpack including COG. And I think you truly care about your version of COG. Thanks for all your work!

**Comment by lawremi** [comment]
Even if the XML is valid? The log should give a stack trace saying where it failed to parse the file.

**Comment by JaguarM** [comment]
Log: https://pastebin.com/gRp9QiDy
Video showing the error: https://youtu.be/Cc3haxXXTEs

**Comment by lawremi** [comment]
As the log shows, the `groupVanilla` option has been used twice (once in the built-in vanilla config, now again in the custom file). It's not allowed to duplicate options, even across files. If you want to modify the Vanilla.xml, just remove the load element for the built-in one from CustomOreGen_Default.xml (after renaming it to CustomOreGen.xml).

**Comment by JaguarM** [comment]
Thanks for your help, I got it working as intended.
