### ISSUE TITLE
Can't replace Mineralogy blocks

### ISSUE THREAD

**Issue by WolfieWaffle** [lawremi/CustomOreGen#218]
If you set a module to replace stone and generate the world, it will work fine. However, if you set it to replace something such as 'mineralogy:shale' and generate the world with the Mineralogy mod, it will not generate in shale. I suspect this is because Mineralogy is loading after CustomOreGeneration. Is there any way to change the generation order?

**Comment by lawremi** [comment]
It's not controllable at the user level. COG does try to load very late, but it's possible that Mineralogy is still coming later (I guess to allow other mods to generate ores first in stone). Is this with the Substitute distribution? That's the only one where load order would matter. The other distribution types almost surely operate after Mineralogy, so you could at least configure those to replace the different stone types.

**Comment by WolfieWaffle** [comment]
What exactly do you mean by replace distribution, I'm still very confused about how COG works. What I did was copy the Vanilla.xml into the custom folder and edited the Vanilla coal section to replace the ReplacesOre element with 'mineralogy:shale' instead of stone. Is there another way of doing it?

**Comment by lawremi** [comment]
You'll need to use just Replaces to replace a specific block. ReplacesOre operates on ore dictionary keys.

**Comment by WolfieWaffle** [comment]
Ah thanks, that was the problem. Sorry for the dumb question.
