### ISSUE TITLE
[Mod compat] OpenCubicChunks

### ISSUE THREAD

**Issue by Shazuli** [lawremi/CustomOreGen#223]
***Hi!***

As the title suggests: Mod compatibility with [OpenCubicChunks](https://minecraft.curseforge.com/projects/opencubicchunks) which stacks chunks for an almost infinite sky and depth.
Right now it fails to generate the ores when OCC is installed whilst without generates them like normal, to note is that it succeeds to remove the vanilla ore generation and leaves a world without ores.

**Comment by lawremi** [comment]
My guess is that the condition in the XML that looks for a specific generator just needs to be changed to allow the OCC generator.

**Comment by Shazuli** [comment]
Do you know where I should start looking? Point me a little, I am pretty new with changing the world generation apart from enable/disable ores from other mods.

**Comment by Shazuli** [comment]
I do not know what to look for @lawremi

**Comment by lawremi** [comment]
Actually, it may be the definition of `COGActive` in `CustomOreGen_Default.xml`. You can check by looking in the world's `CustomOreGen_Options.txt` file. If `COGActive` is `false`, that may be the problem. You can also use debug mode (see the documentation) to see whether COG is generating any distributions.

**Comment by Shazuli** [comment]
It seems like it isn't disabled in the configs of the world. And when enabling debug mode it does indeed draw the wire frames but but not the actual ores. These pictures were also about 1 km away from spawn, but it is the same there too:

![2018-12-18_18 22 32](https://user-images.githubusercontent.com/9884180/50171545-04a8f180-02f3-11e9-8e61-99ae998179ff.png)
![2018-12-18_18 24 47](https://user-images.githubusercontent.com/9884180/50171546-04a8f180-02f3-11e9-87df-46f13850a4fa.png)
(Those floating stone pieces are simply infested stones that randomly generate)

**Comment by lawremi** [comment]
If you enable debug in the config screen, you'll see the deferred population range option. Set it to 0 and regenerate the world. Hopefully those distributions populate. You can play the game that way, with some minor aberrations.

**Comment by Shazuli** [comment]
After some testing with a [cave generator](https://minecraft.curseforge.com/projects/worleys-caves) mod I can assume OCC does not overwrite the current terrain which gives the lack ores from vanilla a explanation.
Something I noticed is the increase of loading time when generating a world without OCC and have COG ores generate like normal while with OCC decreases the loading time as seen from console. This could be explained that COG has quite a few heavy calculations made (obviously), so when OCC is installed simply disables your ore spawning altogether. Which is another point to it not overwriting but simply disabling the ore generation.

**Comment by Shazuli** [comment]
Ok, I missed you replying to me 17 minutes ago.
And by "config screen" you mean Mod Options? It seems like it didn't find a mcmod.info file and therefore can't change any values.
