### ISSUE TITLE
Supplemental caves: Changes to substitution

### ISSUE THREAD

**Issue by keybounce** [lawremi/CustomOreGen#5]
Supplemental caves will wipe out bedrock. They do not place lava at Y=10 and lower. Both of these behaviors are serious changes from normal caves.

Separate, consider restricting to stone, dirt, gravel, and grass -- that way they will behave more like normal caves. These supplemental caves will wipe out villages.

Normal caves will not replace sand, sandstone, or mycelium; I'm not sure if they replace clay. With mod biomes giving different "biome tops" (example: redrock, or "cracked sand" and "cracked dirt"), caves would not replace those prior to a forge version around 1.4.7 / 1.5.1 (not sure exactly when). So it isn't clear if the supplemental caves should continue the "Don't replace biome top blocks except for dirt and grass", or if it should replace mod tops, or if it should replace the sand/sandstone/mycelium that vanilla does not.

Finally, it is possible to run a second cave with a very slightly different outer edge, to turn stone into water or lava, giving water/lava sources in these caves -- see http://www.minecraftforum.net/topic/1107057-146v2-custom-ore-generation-updated-jan-5th/page__st__1240#entry22877781

See also: http://www.minecraftforum.net/topic/1107057-146v2-custom-ore-generation-updated-jan-5th/page__st__1240#entry22907431

**Comment by lawremi** [comment]
Perhaps there is some way to remove gravel only below sealevel?

**Comment by keybounce** [comment]
hmm ...

Same seed, replacing only gravel, spawners, and chests, with air; a height limit of sea level ...

Now, how to do a height limit? I can do a limit based on motherlode distance. I can do absolute Y levels on substitute only.

I could do a first pass veins on those into marker blocks, a substitute on marker blocks below sea level to air, and then a vein pass on markers back into specified blocks. But that kills the spawner's type/nbt. And, it leaves tile entity data for the old chests around.

The "best" solution would be to get early distributions that run at the same time as caves/ravines, as well as the current "late" distributions. Lacking that, I think just removing the gravel/spawners/chests in the way is the best answer. The occasional messed up village is the lesser problem.

**Comment by reteo** [comment]
The issue has been resolved; Extra Caves have been folded into the "Special Rules" XML, and bedrock is explicitly marked as a -1 weight.  Also in the special rules is a "mantle" setup that can be used to fill all air blocks below a certain level with lava.  Used together, these two settings can create natural-looking caverns that don't break bedrock, and that hide the bedrock under a pool of lava.

**Comment by lawremi** [comment]
What about the gravel issue?

**Comment by reteo** [comment]
As far as I can tell, gravel, liquids, sand, and so forth do not move when the cave is carved out; it seems like they are waiting for block updates in order to do their things.  The same thing happens when lava pipes pass through caves.  Or are you referring to a different gravel issue?

**Comment by lawremi** [comment]
Seems good enough for an experimental feature. Closing this issue until major gameplay issues are identified.

**Comment by reteo** [comment]
Sounds like a winning game plan to me.
