### ISSUE TITLE
Way to print out world properties

### ISSUE THREAD

**Issue by retep998** [lawremi/CustomOreGen#50]
While working on oregen for various dimensions, I couldn't find a way to get the name of the current generator. Is there any way to print out things like `dimension.generator` and if not could such a command be added?

**Comment by lawremi** [comment]
Seems like this should be the role of another mod.

**Comment by reteo** [comment]
I don't know about "dimension.generator", but if you choose to use "dimension.generator.class", you can find the name of the mod's dimension generator class.  Usually, the class used in a mod is of the style ChunkProvider(something), where (something) is usually specific to that mod (for example, ChunkProviderEnd or ChunkProviderTwilightForest).
