### ISSUE TITLE
Corrupt chunk

### ISSUE THREAD

**Issue by retep998** [lawremi/CustomOreGen#56]
I don't know what caused this but using COG and PFAA on a server I got a corrupt chunk.
![](http://puu.sh/ex4pl/379b11115f.jpg)

**Comment by lawremi** [comment]
I'm not sure what I'm supposed to see from that screenshot, and there's no way for me to reproduce this.

**Comment by retep998** [comment]
Notice that a lot of ores were replaced with cauldrons and a couple of brewing stands. Also notice the random machine blocks, and down further an entire mass of stone replaced by ladders.
I don't know how to reproduce it either or if COG is even responsible. I'm just documenting it here in case it ever happens again.

**Comment by lawremi** [comment]
I'll close this for now, as this was probably just "random" corruption.
