### ISSUE TITLE
Mystcraft support concerns.

### ISSUE THREAD

**Issue by keybounce** [lawremi/CustomOreGen#6]
See http://www.minecraftforum.net/topic/1107057-146v2-custom-ore-generation-updated-jan-5th/page__st__1200#entry22387162

JRoush's templates for supporting mystcraft ages would tend to leave most ages seriously lacking in ores. This post contains updated templates to ensure that there is an ore distribution of each type in each age.

Additionally, the behavior of instability has changed, significantly. In the current mystcraft API, you can tell a given type of block how many times (average) per chunk it will be generated, and it reports back how much instability that is worth. So the idea of trying to have the symbols determine their own instability is probably out of date.

**Comment by lawremi** [comment]
Please reopen if this is still relevant.

**Comment by keybounce** [comment]
Not necessarily re-opening; just some notes on the current status.

It is no longer necessary for things/populators to report instability to mystcraft; mystcraft now profiles those ores that it has symbols for and knows about. Specifically, it tracks coal, iron, redstone, gold, and diamond.

It does not track anything else. It would be possible for a mod to register symbols for block X, and the user puts down lots of X; that would be something that in theory, could be tracked by the mod responsible for putting down X as additional/bonus instability.

At the moment, that should be regarded as an optional concern. Excessive Lapis, or Emeralds, could be generated (nb: no symbol for those now), as could excessive infused stone, or something. JAMI adds a bunch of symbols, for example.

Solving this is probably outside of the scope of COG.
However, being able to give a "bonus" -- lets just say that I'm in a Slidecraft series with others doing just that (using 1.4.7).

===

Dense ores: The current way that dense ores works is by running ore population multiple times. So, a world with two dense ores symbols gets three sets of ores (or about triple normal). 

Some way to catch the number of dense ores, and multiplying the ore frequencies to match, would solve that. I don't know what the API for dense ores looks like at the moment.
