### ISSUE TITLE
GregTech ore metadata

### ISSUE THREAD

**Issue by retep998** [lawremi/CustomOreGen#61]
GregTech ore blocks use the metadata value to indicate the hardness of ores. If the metadata is not set then all ores will have the lowest hardness and be breakable by a mere wooden pickaxe.

**Comment by Voidi** [comment]
Isn't this what you whant?
https://github.com/lawremi/CustomOreGen/wiki/Documentation#tile-entity-support

**Comment by retep998** [comment]
While GregTech ores do use the NBT field, the point is that they also use the regular metadata field.
For example `<OreBlock block='gregtech:gt.blockores' nbt='{m:500, n:1, id:"GT_TileEntity_Ores"}'>` should actually be `<OreBlock block='gregtech:gt.blockores:3' nbt='{m:500, n:1, id:"GT_TileEntity_Ores"}'>`. Notice the `:3`.

**Comment by lawremi** [comment]
Thanks for pointing this out. The actual meta value to use is an open question. Should it be randomized, e.g. based on the perlin noise field within a cloud? Or just set to a fixed value, on a per-material basis?

**Comment by lawremi** [comment]
Ok, after some investigation, it looks like it is material-dependent. That's easy to replicate in the config.

**Comment by retep998** [comment]
Also, small ores should use a meta value 1 less than the meta for a regular ore.

**Comment by lawremi** [comment]
I didn't precisely adhere to Greg's hardness values, mostly to maintain balance given that we are changing the generation patterns. However, I did follow the rule for small ores.
