### ISSUE TITLE
OreDict in Congifts not 100%

### ISSUE THREAD

**Issue by Draco18s** [lawremi/CustomOreGen#92]
So I've got things like this in my configs for showing options:

	<DisplayState>:= if(?forceExtraOres|blockExists("oreUranium")|blockExists("orePitchblende"),"shown","hidden")</DisplayState>

And I've got a mod-pack author who says that Uranium and Aluminum don't show up, despite having a mod with it (Immersive Engineering, which registers its blocks in pre-init).
http://i.imgur.com/Am5SOQz.png

https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/IEContent.java#L173
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/IEContent.java#L263

**Comment by lawremi** [comment]
It looks like you are checking for whether an *ore* not a *block* exists. I could add `oreExists()`...

**Comment by Draco18s** [comment]
I thought I had checked the code for that check polling the OreDict...yeah:

    public static boolean oreExists(String oreDescription)
    {
    	return OreDictionary.getOres(oreDescription).size() > 0;
    }

From ValidatorIfOreExists...backtracking...
    validator.addGlobalValidator(Node.ELEMENT_NODE, "IfOreExists", new ValidatorIfOreExists.Factory(false));

Which is *not* BlockExists but implies that oreExists already exists.

Correct?

**Comment by lawremi** [comment]
Right, well, there's an element `IfOreExists`. I don't think there's a function in the expression language. But it would be trivial to add. If that's what you mean.

**Comment by Draco18s** [comment]
Ah, yes.  That is the thing I would need, then, yes.  It'd be a lot better than if-or-if-or-ifing by mod or blockname.

**Comment by lawremi** [comment]
Actually, I looked into it, and oreExists() does exist as a function, so I think you have what you need.

**Comment by Draco18s** [comment]
Ok, cool, thanks.  I had looked myself, but didn't find it.
